version: '2'
services:
  tsugi:
    build: ./tsugi
    ports:
      - ${TSUGI_PORT}:80
    volumes:
      - ./tsugi/www:/var/www/html
    depends_on:
       - db
    networks:
      dnet:
        aliases:
          - tsugi
        ipv4_address: ${TSUGI_IP}
    env_file: .env
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    # command: /usr/local/bin/config.sh
  rating:
    build: ./rating
    ports:
      - ${RATING_PORT}:80
    depends_on:
       - db
    volumes:
      - ./rating/www:/var/www/html
    networks:
      dnet:
        aliases:
          - rating
        ipv4_address: ${RATING_IP}
    env_file: .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    # command: /usr/local/bin/config.sh
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PMA_PORT}:80
    depends_on:
      - db
    env_file: .env
    environment:
      - PMA_HOST=${MYSQL_HOST}
      - PMA_PORT=3636
    networks:
      - dnet
  db:
    build: ./db
    ports:
      - 3636:3306
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/config.sh:/docker-entrypoint-initdb.d/config.sh
    networks:
      dnet:
        aliases:
          - db
        ipv4_address: ${DB_IP}
networks:
  dnet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
        gateway: 172.16.239.1