version: '2'
services:
  tsugi:
    build: ./tsugi
    ports:
      - ${TSUGI_PORT}:80
    volumes:
      - ./tsugi/www:/var/www/html
    depends_on:
       - mysql
    command: ["/usr/local/bin/wait-for-it.sh", "${MYSQL_HOST}:${MYSQL_PORT}", "--", "php", "admin/upgrade.php"]
    networks:
      dnet:
        aliases:
          - tsugi
        ipv4_address: ${KECHIRASE_SUBNET}.${TSUGI_IP}
    env_file: .env
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  rating:
    build: ./rating
    ports:
      - ${RATING_PORT}:80
    depends_on:
       - mysql
    volumes:
      - ./rating/www:/var/www/html
    networks:
      dnet:
        aliases:
          - rating
        ipv4_address: ${KECHIRASE_SUBNET}.${RATING_IP}
    env_file: .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_HOST=${MYSQL_HOST}
    networks:
      - dnet
  mysql:
    build: ./mysql
    ports:
      - ${MYSQL_PORT}:3306
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./mysql/mysql:/var/lib/mysql
      - ./mysql/config.sh:/docker-entrypoint-initdb.d/config.sh
    networks:
      dnet:
        aliases:
          - mysql
        ipv4_address: ${KECHIRASE_SUBNET}.${MYSQL_IP}
networks:
  dnet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${KECHIRASE_SUBNET}.0/24
        gateway: ${KECHIRASE_SUBNET}.1