FROM php:7.2-apache

RUN docker-php-ext-install \
    pdo \
    pdo_mysql

RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    curl \
    git \
    mysql-client

COPY ./www .

RUN a2enmod -q rewrite dir expires headers

COPY ./wait-for-mysql.sh /usr/local/bin
RUN chmod u+x /usr/local/bin/wait-for-mysql.sh

ENTRYPOINT ["/usr/local/bin/wait-for-mysql.sh"]
CMD ["apache2-foreground"]

