echo "============Initializing db============"

mysql -e "GRANT ALL ON ${MYSQL_DATABASE}.* TO ${MYSQL_USER}@'localhost' IDENTIFIED BY ${MYSQL_PASSWORD}"
mysql -e "GRANT ALL ON ${MYSQL_DATABASE}.* TO ${MYSQL_USER}@'127.0.0.1' IDENTIFIED BY ${MYSQL_PASSWORD}"
mysql -e "GRANT ALL ON ${MYSQL_DATABASE}.* TO ${MYSQL_USER}@${DB_IP} IDENTIFIED BY ${MYSQL_PASSWORD}"