FROM mysql:5.7

#COPY config.sh /docker-entrypoint-initdb.d
#RUN chmod u+x /docker-entrypoint-initdb.d/config.sh
#COPY config.sql /docker-entrypoint-initdb.d
#RUN chmod u+x /docker-entrypoint-initdb.d/config.sql
